config/routes.rb
MyFirstApp::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'registrations' }

  get "admin/retrainclassifier"
  get "admin/makecategories"
  get "admin/makesituations"
  get "admin/index"
  get "admin/makesomeplanswithstats"
  get "admin/buildclusterlist"

  get "categories/index"
  get "categories/show"
  get "categories/edit"
  get "categories/create"
  get "categories/update"
  get "categories/destroy"

  get "help/index"
  get "help/about"
  get "help/terms"
  get "help/privacy"

  # get '/chatroom' => 'chats#room', :as => :chat
  # post '/new_message' => 'chats#new_message', :as => :new_message

  match '/help' => 'help#index'

  resources :mobile_session, :only => [:create, :destroy]
  match '/mobile/login' => 'mobile_session#create'
  match '/mobile/logout' => 'mobile_session#destroy'

  match '/auth/:provider/callback' => 'authentications#create'

  match "/auth/failure" => redirect("/")

  resources :me, :only => [:index, :show]
  match '/me/test' => 'me#test'
  match 'me/follow/:id' => 'me#follow'
  match 'me/unfollow/:id' => 'me#unfollow'
  match '/me/contact/:id' => 'me#contact'
  match '/me/messages/:id' => 'me#messages'
  match '/me/send_message/:id' => 'me#send_message', :as => 'send_message'
  match '/me/nearby/:id' => 'me#find_nearby_people', :as => 'nearby'

  resources :answers, :only => [:index]
  resources :badges

  resources :authentications

  resources :notifications, :only => [:getLatest, :getLatestCount] do
    collection do
      get 'getLatestCount'
      get 'getLatest'
    end
  end

  resources :notes, :only => [:create, :update, :destroy]
  #get "notes/index"
  #get "notes/show"
  #get "notes/create"
  #get "notes/update"
  #get "notes/new"

  resources :situations do
    resources :plans, :only => [:index]
    resources :users, :only => [:index]
    resources :stats, :only => [:index]
    resources :notes, :only => [:index]

    get 'complete_after_sign_in'

    collection do
      #post 'rate'
      get 'getWhatKeywords'
      get 'getWhereKeywords'
      get 'getWhenKeywords'
      post 'start'
      post 'next'
      get 'listby'
      get 'updatecategory'
      get 'linkaplan'
      get 'getLatest'
    end

    member do
      post 'rate'
      get 'rate'
      get 'vote_up'
      get 'vote_down'
      get 'quickshow'
    end

  end

  resources :admin

  resources :categories do
    resources :situations

    collection do
      get 'findrelated'
    end
  end

  get "home/index"
  get "home/error404"
 
  resources :plans do
    get 'complete_after_sign_in'
    
    member do
      post 'rate'
      get 'rate'
      get 'vote_up'
      get 'vote_down'
    end

  resources :users
    collection do
      get 'listby'
      get 'listplansby'
      get 'search'
      get 'updatecategory'
    end
  end

  resources :messages
  post '/messages/new' => 'messages#new', :as => :new_message

  resources :chats
  
  resources :filters

  root :to => "home#index"

  match "*path", :to => "application#routing_error"
  
end


app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id"
  has_many :categories, :through => :filter_categories_associations
  has_many :filter_categories_associations

  attr_accessible :what, :when_from, :when_to, :location, :location_lat, :location_lng, 
                  :category, :by_category, :by_location, :distance, :apply_filter

  attr_reader :category

  validates_presence_of :what, :location, :when_from, :when_to
  validates_uniqueness_of :what, :length => { :minimum => 5 }

  validates_numericality_of :distance, 
    :length => { :maximum => 4, :minimum => 1},
    :format => /\d+/
  
  geocoded_by :location
    reverse_geocoded_by :location_lat, :location_lng, :address => :location
    after_validation :geocode, :reverse_geocode, :if => :location_changed?

  def category=(ids)
    self.category_ids = ids.split(",")
  end

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  # GET /filters
  # GET /filters.xml
   def index
     if current_user
      @filters = Filter.where(user_id: current_user.id)
 
      respond_to do |format|
        format.html { render :action => "index", 
                             :layout => "layouts/application2"
                    } # index.html.erb
        format.xml  { render :xml => @filters }
      end
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /filters/1
  # GET /filters/1.xml
  def show
    if current_user
      @filter = Filter.find(params[:id])

      respond_to do |format|
        format.html { render :action => "show", 
                             :layout => "layouts/application2"
                    } # show.html.erb
        format.xml  { render :xml => @filter }
      end
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /filters/new
  # GET /filters/new.xml
  def new
    if current_user
      @filter = Filter.new

      respond_to do |format|
        format.html { render :action => "new", 
                             :layout => "layouts/application2"
                    } # new.html.erb
        # format.json  { render :json => @categories.map{|c| [c.name, c.id]} }
      end
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /filters/1/edit
  def edit
    if current_user
      @filter = Filter.find(params[:id])
      # @categories = Category.where("name LIKE ?", "%#{params[:q]}%")

      respond_to do |format|
        format.html { render :action => "edit", :layout => "layouts/application2"  }
        # format.json { render :json => @categories.map{|c| [c.name, c.id]} }
      end
    else
      redirect_to '/users/sign_in'
    end
  end

  # POST /filters
  # POST /filters.xml
  def create
    @filter = Filter.new(params[:filter])
    @filter.user_id = current_user.id

    respond_to do |format|
      if @filter.save
        format.html { redirect_to(@filter, :notice => 'Filter was successfully created.') }
        format.xml  { render :xml => @filter, :status => :created, :location => @filter }
      else
        format.html { render :action => "new", :layout => "layouts/application2"  }
        format.xml  { render :xml => @filter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /filters/1
  # PUT /filters/1.xml
  def update
    @filter = Filter.find(params[:id])

    respond_to do |format|
      if @filter.update_attributes(params[:filter])
        format.html { redirect_to(@filter, :notice => 'Filter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit", :layout => "layouts/application2" }
        format.xml  { render :xml => @filter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.xml
  def destroy
    @filter = Filter.find(params[:id])
    @filter.destroy

    respond_to do |format|
      format.html { redirect_to(filters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> found:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul id="element-list">

    <li class="form-element">
      <%= f.label "By #{current_user.username}", class: "field-title" %>
    </li>
    <li class="form-element">
      <%= f.label :what, "Filter Title", class: "field-title" %>
      <div class="my-input-field">
        <%= f.text_field :what, class: "my-field"  %>
      </div>
    </li>
    <li class="form-element">
        <%= f.check_box :apply_filter, class: "check-box" %>
        <%= f.label :apply_filter, "Apply this filter", class: "field-title" %>
    </li>
    <li class="form-element" id="checkbox">
        <%= f.check_box :by_location, class: "check-box" %>
        <%= f.label :by_location, "Filter by Location", class: "field-title" %>
    </li>
    <li class="form-element" id="option">
    <%= f.label :distance, "Distance", class: "field-title" %>
      <div class="mini-guide">(default is 5km)</div> 
      <div class="my-input-field">
        <%= f.text_field :distance, class: "my-field", :maxlength => 4 %>
      </div>
    
    <%= f.label :location, class: "field-title" %>
        <div class="my-input-field-auto-height">
        <div class="my-input-field-auto-height-top">
          <div class="my-input-field-auto-height-bottom">
            <%= f.text_field :location, class: "my-field", id: "where_are_you" %>
          </div>
        </div>
      </div>
      <div id="where_map" style="width:300px;height:300px;margin-top:4px;margin-bottom:4px;"></div>
      <div class="mini-guide">Drag and drop the red pin to locate your exact place on the map.</div>
      <%= f.hidden_field :location_lat %>
      <%= f.hidden_field :location_lng %>
    </li>

    <li class="form-element" id="checkbox2">
      <%= f.check_box :by_category, class: "check-box" %>
      <%= f.label :by_category, "Filter by Category", class: "field-title" %>
    </li>
    <li class="form-element" id="option2">
      <div class="my-input-field">
        <%= f.text_field :category, class: "my-field", id: "filter_c", "data-pre" => @filter.categories.map(&:attributes).to_json %>
      </div>
    </li>
    <li class="form-element">
      <%= f.label :when_from, "Start Date", class: "field-title" %>
        <div class="my-input-field date-field">
          <%= f.text_field :when_from, class: "my-field datepicker", id: "when_from" %>
        </div>
    </li>
    <li class="form-element">
      <%= f.label :when_to, "End Date", class: "field-title" %>
        <div class="my-input-field date-field">
          <%= f.text_field :when_to, class: "my-field datepicker", id: "when_to" %>
        </div>
    </li>

  <br />

  <div class="actions">
    <a href="#" class="submit_link button">Finish<span></span></a>
  </div>
</ul>
<% end %>

<link rel="stylesheet" href="/css/forms.css" type="text/css" media="all" />
<script type="text/javascript" src="/js/datepicker.js"></script>
  <script>
    $(document).ready(function() {
        $("#when_from").datepicker({
          showOn: 'focus', buttonText: "Select",dateFormat: "MM d, yy "+ date_obj_time 
        });
        $("#when_to").datepicker({
          showOn: 'focus', buttonText: "Select",dateFormat: "MM d, yy "+ date_obj_time 
        });
        $(".ui-datepicker-trigger").append("<span></span>");
    });

    $("#checkbox").click(function () {
      $("#option").toggle("slow");
    });
    $("#checkbox2").click(function () {
      $("#option2").toggle("slow");
    });
  </script>
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<% if  Rails.env.production? %>
     <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA91Zz5Nv-onIUJcE_k7I9cN7Ey_GW_kIw&sensor=false"></script>
<% else %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCEgzy4o-lMybHPr4umvxpKIdqEStrA_Ec&sensor=false"></script>
<% end %>
<script type="text/javascript" src="/js/next.js"></script>
<script type="text/javascript" src="/js/mapper.js"></script>
<script type="text/javascript" src="/js/next-map.js"></script>

app/views/filters/edit.html.erb
<h1>Editing filter</h1>

<%= render 'form' %>

<div class="actions">
    <a href="<%= filter_path %>" class="submit_link button">Cancel<span></span></a>
</div>

app/views/filters/index.html.erb
<h1>Listing filters</h1>
  <% unless @filters.empty? %>
    <table>
      <theader>
        <th>Filter Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Action</th>
      </theader>

    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.what %></td>
        <td><%= filter.when_from.strftime("%B %e, %Y") %></td>
        <td><%= filter.when_to.strftime("%B %e, %Y") %></td>
        <td>
          <a href="<%= filter_path(filter) %>" class="button">Show<span></span></a> 
          <a href="<%= edit_filter_path(filter) %>" class="button">Edit<span></span></a> 
          <a href="<%= filter_path(filter) %>" data-method="delete" data-confirm="Are you sure?" class="button">Delete<span></span></a>
        </td> 
      </tr>
    <% end %>
    </table>

  <% else %>
  <p>
    No filters saved.
  </p>
  <% end %>
    
<br />

<a href="<%= new_filter_path %>" class="button">Create New Filter<span></span></a>

app/views/filters/new.html.erb
<h1>New filter</h1>

<%= render 'form' %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<h2><%= @filter.what %></h2>
<br />
<% if @filter.by_location == 1 %>
<p>
  <strong>Location</strong>
  <%= @filter.location %>
<br>
  <strong>Distance</strong>
  <%= @filter.distance %> km.
</p>
<% end %>
<% if @filter.by_category == 1 %>
<p>
  <strong>Category Name(s):</strong>
  <ul>
    <% for category in @filter.categories %>
    <li><%= category.name %></li>
    <% end %>
    </ul>
</p>
<% end %>
<p>
  <strong>Start Date</strong>
  <%= @filter.when_from.strftime("%B %e, %Y") %>
</p>
<p>
  <strong>End Date</strong>
  <%= @filter.when_to.strftime("%B %e, %Y") %>
</p>


<br />
<br />
<div class="actions">
  <a href="<%= filters_path %>" class="button">View My Filters<span></span></a>
  <a href="<%= edit_filter_path(@filter) %>" class="button">Edit<span></span></a>
  <a href="<%= filter_path(@filter) %>" data-method="delete" data-confirm="Are you sure?" class="button">Delete<span></span></a>
</div>

<link rel="stylesheet" href="/css/forms.css" type="text/css" media="all" />